### ISSUE TITLE
proceso de negocio bizaagi

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-proceso-de-negocio-con-bizagi-disttecpersis#2]
[Proceso.de.negocio.pdf](https://github.com/SistemasTecTlaxiaco/practica-proceso-de-negocio-con-bizagi-disttecpersis/files/7377671/Proceso.de.negocio.pdf)

**Comment by KarlaV0** [comment]
18%
En la portada se encuentra información que forma parte del desarrollo, lo cual distorsiona la portada, pero si se encuentran todos los datos. Revisarlo
Recomendación: Justificar los textos

[5. Rúbrica reporte de practica Bizagi.pdf](https://github.com/SistemasTecTlaxiaco/practica-proceso-de-negocio-con-bizagi-disttecpersis/files/7377591/5.Rubrica.reporte.de.practica.Bizagi.pdf)

**Comment by josealfredo79** [comment]
El proceso de negocio debe ser en el cual se va a desarrollar el nuevo modelo ..

**Comment by josealfredo79** [comment]
Cuando realizan su daily scrum que es una comunicacion efectiva que realizan diaramente, aqui se denota poca comunicacion

**Comment by josealfredo79** [comment]
Ademas con la revisión del scrum y tambien de la restrospectiva que son artefactos importantes para reflexionar sobre el proyecto al estar ausentes es muy poca la productividad

**Comment by josealfredo79** [comment]
Se debe replantear los tres trabajos anteiores...por favor.
