### ISSUE TITLE
proceso de negocio con bizagi

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-proceso-de-negocio-con-bizagi-disttecpersis#3]
[Proceso.de.negocio.pdf](https://github.com/SistemasTecTlaxiaco/practica-proceso-de-negocio-con-bizagi-disttecpersis/files/7412290/Proceso.de.negocio.pdf)

**Comment by KarlaV0** [comment]
19%

**Comment by josealfredo79** [comment]
El proceso de Negocio debe ser del modelo nuevo que van a diseñar...aqui como no hay una buena comunicación ni revisan el moodle estan haciendo practicas sin tener la información

**Comment by salathiel1999** [comment]
[proceso-de-negocio-con-bizagi.pdf](https://github.com/SistemasTecTlaxiaco/practica-proceso-de-negocio-con-bizagi-disttecpersis/files/7827821/proceso-de-negocio-con-bizagi.pdf)

**Comment by salathiel1999** [comment]
ya lo corregimos desde hace tiempo

**Comment by josealfredo79** [comment]
Revisando bien...hace falta la lista de figuras, las imagenes deben tener un pie de imagen

**Comment by josealfredo79** [comment]
La calificacion no esta bien asignada porque hace faltan lo antes mencionado, para calificar y evaluar hay que hacerlo con responsabilida no se puede asignar la calificacion de 19, por favor
